name: CD - Deploy to AKS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: List repo contents
        run: |
          pwd
          ls -R

      - name: Build and Push Backend Images
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/product_service:latest ./example-3/backend/product_Service
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/product_service:latest

          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/order_service:latest ./example-3/backend/order_Service
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/order_service:latest


      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest ./example-3/frontend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER }} --overwrite-existing

      - name: Deploy to AKS
        run: |
          
          kubectl apply -f ./example-3/k8s/prometheus-deployment.yaml
          kubectl apply -f ./example-3/k8s/prometheus-rbac.yaml
          kubectl apply -f ./example-3/k8s/grafana-deployment.yaml
          kubectl apply -f ./example-3/k8s/product-db.yaml
          kubectl apply -f ./example-3/k8s/order-db.yaml
          kubectl apply -f ./example-3/k8s/product-service.yaml
          kubectl apply -f ./example-3/k8s/order-service.yaml
          kubectl apply -f ./example-3/k8s/frontend-service.yaml
          kubectl apply -f ./example-3/prometheus/prometheus.yml
